routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'HomeController@index');
Route::resource('schedules', 'ScheduleController');
Route::resource('servers', 'ServerController');
Route::resource('databases', 'DatabaseController');
Route::post('databases/{id}/backup', 'DatabaseController@backup')->name('databases.backup');
Route::resource('backups', 'BackupController', ['only' => [
	'index', 'show', 'destroy'
]]);

resources/views/databases/create.blade.php
@extends('layouts.app')

@section('content')
<div class='content-container'>
	<h1>Create Database</h1>
	<form method="POST" action="{{ route('databases.store') }}">
		{{ csrf_field() }}
		<select   name='server_id'>
			<option value=0 disabled>Server</option>
			@foreach($servers as $server)
				<option value="{{ $server->id }}"  {{ (old('server_id') == $server->id) ? 'selected' : '' }} >{{ $server->name }} ({{ $server->serverType->type }})</option>
			@endforeach
		</select>

		<div class="form-group">
			<input class="{{ $errors->has('name') ? ' has-error' : '' }}" type="text" placeholder="Name" name="name" value="{{ old('name') }}" required autofocus>

			@if ($errors->has('name'))
				<span class="help-block">
					<strong>{{ $errors->first('name') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<textarea class="{{ $errors->has('description') ? ' has-error' : '' }}" type="text" placeholder="Description" name="description" >{{ old('description') }}</textarea>

			@if ($errors->has('description'))
				<span class="help-block">
					<strong>{{ $errors->first('description') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<button type="submit">
				Create
			</button>

			<a class="button" href="{{ route('databases.index') }}">
				Back
			</a>
		</div>
	</form>
</div>
    
@endsection

resources/views/databases/edit.blade.php
@extends('layouts.app')
<?php
	$server_id = (old('server_id')) ? old('server_id') : $database->server->id;

?>
@section('content')
<div class='content-container'>
	<h1>Edit Database</h1>
	<form method="POST" action="{{ route('databases.update', ['id' => $database->id]) }}">
		{{ csrf_field() }}
		{{ method_field('PATCH') }}
		<select   name='server_id'>
			<option value=0 disabled>Server</option>
			@foreach($servers as $server)
				<option value="{{ $server->id }}" {{ ($server->id == $server_id) ? 'selected' : '' }} >{{ $server->name }} ({{ $server->serverType->type }})</option>
			@endforeach
		</select>

		<div class="form-group">
			<input class="{{ $errors->has('name') ? ' has-error' : '' }}" type="text" placeholder="Name" name="name" value="{{ (old('name')) ? old('name') : $database->name }}" required autofocus>

			@if ($errors->has('name'))
				<span class="help-block">
					<strong>{{ $errors->first('name') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<textarea class="{{ $errors->has('description') ? ' has-error' : '' }}" type="text" placeholder="Description" name="description" >{{ (old('description')) ? old('description') : $database->description }}</textarea>

			@if ($errors->has('description'))
				<span class="help-block">
					<strong>{{ $errors->first('description') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<button type="submit">
				Save
			</button>

			<a class="button" href="{{ route('databases.index') }}">
				Back
			</a>
		</div>
	</form>
</div>
    
@endsection

resources/views/databases/index.blade.php
@extends('layouts.app')

@section('content')
<div class='content-container'>
	<div class='content-header'>
		<a class='button' href="{{ route('databases.create') }}">Add Database</a>
	</div>
	
	<div class='standard-list'>
		@if($databases->count())
			<div class='standard-list-row standard-list-header'>
				<span>Name</span>
				<span>Description</span>
				<span>Server</span>
				<span>Action</span>
			</div>
		@endif
		@each('databases.index.row', $databases, 'database', 'databases.index.empty')
	</div>
</div>
    
@endsection

resources/views/databases/show.blade.php
@extends('layouts.app')

@section('content')
<div class='content-container'>
	<div class='standard-show'>
		<h2>{{ $database->name }}</h2>
		<h4 class='description'>{{ $database->description }}</h4>
		<ul class='details'>
			<li><strong>Server: </strong>{{ $database->server->name }} ({{ $database->server->serverType->type }})</li>
		</ul>
		<a class="button" href="{{ route('databases.index') }}">
			Back to Databases
		</a>
	</div>
</div>
    
@endsection