routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'HomeController@index');
Route::resource('schedules', 'ScheduleController');
Route::resource('servers', 'ServerController');
Route::resource('databases', 'DatabaseController');
Route::post('databases/{id}/backup', 'DatabaseController@backup')->name('databases.backup');
Route::resource('backups', 'BackupController', ['only' => [
	'index', 'show', 'destroy'
]]);

app/Server.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Crypt;

class Server extends Model {
	protected $hidden = ['password',
						 'ssh_password'];
	protected $guarded = [];

	public function user() {
		return $this->belongsTo('App\User');
	}

	public function databases() {
		return $this->hasMany('App\Database');
	}
	
	public function serverType() {
		return $this->belongsTo('App\ServerType');
	}

	public function decrypt() {
		$this->password = Crypt::decrypt($this->password);
		$this->ssh_password = Crypt::decrypt($this->ssh_password);

		return $this;
	}
}

app/ServerType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ServerType extends Model
{
    public $timestamps = false;

    public function servers () {
    	return $this->hasMany('App\Server');
    }

    public function databases () {
    	return $this->hasMany('App\Database', 'App\Server');
    }
}

app/Http/Controllers/ServerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Server;
use App\ServerType;
use Validator;
use Auth;
use Crypt;

class ServerController extends Controller
{
    public function index()
    {

    	$user = Auth::user();
    	$servers = $user->servers()
    					->with('serverType')
    					->get();

        return response()->json(compact('servers'));
    }

    public function create() {
    	$server_types = ServerType::get();
        $ports = $server_types->keyBy('id')
                              ->map(function ($server_type) { 
                                    return $server_type['default_port'];
                                });

        return response()->json(compact('server_types', 'ports'));
    }

    public function edit($id) {
        $server_types = ServerType::get();
        $server = Server::with('serverType')->find($id);
        $ports = $server_types->keyBy('id')
                              ->map(function ($server_type) { 
                                    return $server_type['default_port'];
                                });
        $server = Server::with('serverType')->find($id);

        return response()->json(compact('server', 'server_types', 'ports'));
    }

    public function store(Request $request) {
    	Validator::make($request->all(), [
		    'server_type_id' => 'required|exists:server_types,id',
            'name' => 'required|max:255',
            'address' => 'required|max:255',
            'port' => 'required|numeric|max:65535',
            'username' => 'required|max:255',
            'password' => 'required|max:255',
            'ssh_username' => 'required|max:255',
            'ssh_password' => 'required|max:255'
		])->validate();

		

		$server = Auth::user()->servers()->create([
				'server_type_id' => $request->server_type_id,
				'name' => $request->name,
				'description' => $request->description,
				'address' => $request->address,
				'port' => $request->port,
				'username' => $request->username,
				'password' => Crypt::encrypt($request->password),
				'ssh_username' => $request->ssh_username,
				'ssh_password' => Crypt::encrypt($request->ssh_password),
		]);

		$server->save();
    }

    public function update(Request $request, $id) {

    	Validator::make($request->all(), [
		    'server_type_id' => 'required|exists:server_types,id',
            'name' => 'required|max:255',
            'address' => 'required|max:255',
            'port' => 'required|numeric|max:65535',
            'username' => 'required|max:255',
            'password' => 'max:255',
            'ssh_username' => 'required|max:255',
            'ssh_password' => 'max:255'
		])->validate();

		$server = Server::find($id);

		$server->name = $request->name;
		$server->description = $request->description;
		$server->address = $request->address;
		$server->port = $request->port;
		$server->username = $request->username;

		if ($request->password) {
			$server->password = $request->password;
		}

		$server->ssh_username = $request->ssh_username;
			
		if ($request->ssh_password) {
			$server->ssh_password = $request->ssh_password;
		}

		$server->save();
    }

    public function show($id) {
		$server = Server::with('serverType')->find($id);
        return response()->json(compact('server'));
		
    }

    public function destroy($id) {
    	$server = Server::find($id);
    	$server->delete();
    }
}

resources/views/servers/create.blade.php
@extends('layouts.app')

@push('scripts')
<script type="text/javascript">
	var form;

	window.onload = function () {
		form = new Vue({
		    el: '.content-container form',
		    data: {
		    	server_type_id:  {{ (old('server_type_id')) ? old('server_type_id') : 0 }},
		    	ports: {!! $server_types->keyBy('id')
		    							->map(function ($server_type) { 
		    								return $server_type['default_port'];
		    							})->toJSON() !!},
		    	port: {{ (old('port')) ? old('port') : 0 }}
		    },
		    watch: {
		    	server_type_id: function () {
		    		if (port = this.ports[this.server_type_id]) {
		    			this.port = port;
		    		}
		    	}
		    }
		});	
	}
</script>
@endpush

@section('content')
<div class='content-container'>
	<h1>Create Server</h1>
	<form method="POST" action="/servers">
		{{ csrf_field() }}

		<select  v-model="server_type_id" name='server_type_id'>
			<option value=0 disabled>Server Type</option>
			@foreach($server_types as $server_type)
				<option value="{{ $server_type->id }}">{{ $server_type->type }}</option>
			@endforeach
		</select>


		<div class="form-group">
			<input class="{{ $errors->has('name') ? ' has-error' : '' }}" type="text" placeholder="Name" name="name" value="{{ old('name') }}" required autofocus>

			@if ($errors->has('name'))
				<span class="help-block">
					<strong>{{ $errors->first('name') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<textarea class="{{ $errors->has('description') ? ' has-error' : '' }}" type="text" placeholder="Description" name="description" >{{ old('description') }}</textarea>

			@if ($errors->has('description'))
				<span class="help-block">
					<strong>{{ $errors->first('description') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<input class="{{ $errors->has('address') ? ' has-error' : '' }}" type="text" placeholder="Address" name="address" value="{{ old('address') }}">

			@if ($errors->has('address'))
				<span class="help-block">
					<strong>{{ $errors->first('address') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<input class="{{ $errors->has('port') ? ' has-error' : '' }}" type="number" v-model="port" placeholder="Port" name="port" >

			@if ($errors->has('port'))
				<span class="help-block">
					<strong>{{ $errors->first('port') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<input class="{{ $errors->has('username') ? ' has-error' : '' }}" type="text" placeholder="Username" name="username" value="{{ old('username') }}">

			@if ($errors->has('username'))
				<span class="help-block">
					<strong>{{ $errors->first('username') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<input class="{{ $errors->has('password') ? ' has-error' : '' }}" type="password" placeholder="Password" name="password">

			@if ($errors->has('password'))
				<span class="help-block">
					<strong>{{ $errors->first('password') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<input class="{{ $errors->has('ssh_username') ? ' has-error' : '' }}" type="text" placeholder="SSH Username" name="ssh_username" value="{{ old('ssh_username') }}">

			@if ($errors->has('ssh_username'))
				<span class="help-block">
					<strong>{{ $errors->first('ssh_username') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<input class="{{ $errors->has('ssh_password') ? ' has-error' : '' }}" type="password" placeholder="SSH Password" name="ssh_password" >

			@if ($errors->has('ssh_password'))
				<span class="help-block">
					<strong>{{ $errors->first('ssh_password') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<button type="submit">
				Create
			</button>

			<a class="button" href="\servers">
				Back
			</a>
		</div>
	</form>
</div>
    
@endsection

resources/views/servers/edit.blade.php
@extends('layouts.app')

@push('scripts')
<script type="text/javascript">
	var form;

	window.onload = function () {
		form = new Vue({
		    el: '.content-container form',
		    data: {
		    	server_type_id:  {{ (old('server_type_id')) ? old('server_type_id') : $server->server_type_id }},
		    	ports: {!! $server_types->keyBy('id')
		    							->map(function ($server_type) { 
		    								return $server_type['default_port'];
		    							})->toJSON() !!},
		    	port: {{ (old('port')) ? old('port') : $server->port }}
		    },
		    watch: {
		    	server_type_id: function () {
		    		if (port = this.ports[this.server_type_id]) {
		    			this.port = port;
		    		}
		    	}
		    }
		});	
	}
</script>
@endpush

@section('content')
<div class='content-container'>
	<h1>Edit Server</h1>
	<form method="POST" action="{{ route('servers.update', ['id' => $server->id]) }}">
		{{ csrf_field() }}
		{{ method_field('PATCH') }}

		<select  v-model="server_type_id" name='server_type_id'>
			<option value=0 disabled>Server Type</option>
			@foreach($server_types as $server_type)
				<option value="{{ $server_type->id }}">{{ $server_type->type }}</option>
			@endforeach
		</select>


		<div class="form-group">
			<input class="{{ $errors->has('name') ? ' has-error' : '' }}" type="text" placeholder="Name" name="name" value="{{ (old('name')) ? old('name') : $server->name }}" required autofocus>

			@if ($errors->has('name'))
				<span class="help-block">
					<strong>{{ $errors->first('name') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<textarea class="{{ $errors->has('description') ? ' has-error' : '' }}" type="text" placeholder="Description" name="description" >{{ (old('description')) ? old('description') : $server->description }}</textarea>

			@if ($errors->has('description'))
				<span class="help-block">
					<strong>{{ $errors->first('description') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<input class="{{ $errors->has('address') ? ' has-error' : '' }}" type="text" placeholder="Address" name="address" value="{{ (old('address')) ? old('address') : $server->address }}">

			@if ($errors->has('address'))
				<span class="help-block">
					<strong>{{ $errors->first('address') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<input class="{{ $errors->has('port') ? ' has-error' : '' }}" type="number" v-model="port" placeholder="Port" name="port" >

			@if ($errors->has('port'))
				<span class="help-block">
					<strong>{{ $errors->first('port') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<input class="{{ $errors->has('username') ? ' has-error' : '' }}" type="text" placeholder="Username" name="username" value="{{ (old('username')) ? old('username') : $server->username }}">

			@if ($errors->has('username'))
				<span class="help-block">
					<strong>{{ $errors->first('username') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<input class="{{ $errors->has('password') ? ' has-error' : '' }}" type="password" placeholder="Password" name="password">

			@if ($errors->has('password'))
				<span class="help-block">
					<strong>{{ $errors->first('password') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<input class="{{ $errors->has('ssh_username') ? ' has-error' : '' }}" type="text" placeholder="SSH Username" name="ssh_username" value="{{ (old('ssh_username')) ? old('ssh_username') : $server->ssh_username }}">

			@if ($errors->has('ssh_username'))
				<span class="help-block">
					<strong>{{ $errors->first('ssh_username') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<input class="{{ $errors->has('ssh_password') ? ' has-error' : '' }}" type="password" placeholder="SSH Password" name="ssh_password" >

			@if ($errors->has('ssh_password'))
				<span class="help-block">
					<strong>{{ $errors->first('ssh_password') }}</strong>
				</span>
			@endif
		</div>

		<div class="form-group">
			<button type="submit">
				Save
			</button>

			<a class="button" href="\servers">
				Back
			</a>
		</div>
	</form>
</div>
    
@endsection

resources/views/servers/index.blade.php
@extends('layouts.app')

@section('content')
<div class='content-container'>
	<div class='content-header'>
		<a class='button' href="servers/create">Add Server</a>
	</div>
	
	<div class='standard-list'>
		@if($servers->count())
			<div class='standard-list-row standard-list-header'>
				<span>Name</span>
				<span>Address</span>
				<span>Port</span>
				<span>Action</span>
			</div>
		@endif
		@each('servers.index.row', $servers, 'server', 'servers.index.empty')
	</div>
</div>
    
@endsection

resources/views/servers/show.blade.php
@extends('layouts.app')

@section('content')
<div class='content-container'>
	<div class='standard-show'>
		<h2>{{ $server->name }} ({{ $server->servertype->type }})</h2>
		<h4 class='description'>{{ $server->description }}</h4>
		<ul class='details'>
			<li><strong>Address: </strong>{{ $server->address }} ({{ $server->port }})</li>
			<li><strong>Username: </strong>{{ $server->username }}</li>
			<li><strong>Password: </strong>************</li>
			<li><strong>SSH Username: </strong>{{ $server->ssh_username }}</li>
			<li><strong>SSH Password: </strong>************</li>
			
		</ul>
		<a class="button" href="{{ route('servers.index') }}">
			Back to Servers
		</a>
	</div>
</div>
    
@endsection