routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'HomeController@index');
Route::resource('schedules', 'ScheduleController');
Route::resource('servers', 'ServerController');
Route::resource('databases', 'DatabaseController');
Route::post('databases/{id}/backup', 'DatabaseController@backup')->name('databases.backup');
Route::resource('backups', 'BackupController', ['only' => [
	'index', 'show', 'destroy'
]]);

resources/views/databases/index/empty.blade.php
<span class="empty-state">
No databases have been added yet.
</span>

resources/views/databases/index/row.blade.php
<div class='standard-list-row'>
	<span>
		{{ $database->name }} 
	</span>
	<span>{{ $database->description }}</span>
	<span>{{ $database->server->name }} ({{ $database->server->serverType->type }})</span>
	<span>
		<a class='button button-row' href="{{ route('databases.edit', ['id' => $database->id]) }}">Edit</a>
		<a class='button button-row' href="{{ route('databases.backup', ['id' => $database->id]) }}">Backup</a>
		<form  class='delete-form' method="POST" action="{{ route('databases.destroy', ['id' => $database->id]) }}">
			{{ csrf_field() }}
			{{ method_field('DELETE') }}
			<button class='button-row'">Delete</button>
		</form>
	</span>
</div>